# Generated by Django 4.1.6 on 2023-02-07 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_image_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='name',
        ),
    ]
