# Generated by Django 4.1.6 on 2023-02-07 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_remove_wishlist_slug_wishlist_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='product',
            new_name='products',
        ),
    ]
