# Generated by Django 4.1.6 on 2024-01-03 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
    ]
