# fly.toml app configuration file generated for maniva-store-front on 2024-01-03T22:14:03-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "maniva-store-front"
primary_region = "gru"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
